# Generated by Django 2.0 on 2018-02-20 16:48

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adicional',
            fields=[
                ('codigo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('nombre', models.CharField(max_length=25)),
                ('apellidos', models.CharField(max_length=40)),
                ('telefono', models.CharField(max_length=9, validators=[django.core.validators.MinLengthValidator(9)])),
                ('saldo', models.FloatField(default=0)),
                ('numero_cuenta', models.CharField(help_text='Compuesto del IBAN (ES) MAS 8 digitos', max_length=10, unique=True)),
                ('foto', models.ImageField(default='imgUsuarios/default.jpg', upload_to='imgUsuarios/')),
            ],
        ),
        migrations.CreateModel(
            name='Inscriben',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Liga',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30, unique=True)),
                ('coste_inscripcion', models.FloatField()),
                ('categoria', models.CharField(choices=[('PLATA', 'Plata'), ('NOVA', 'Nova'), ('AK', 'AK'), ('SUPREME', 'Supreme'), ('GLOBAL', 'Global')], default='PLATA', max_length=10)),
                ('imagenLiga', models.ImageField(default='imgLigas/default.png', upload_to='imgLigas/')),
            ],
        ),
        migrations.CreateModel(
            name='Skin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('tipo', models.CharField(choices=[('Covert Sniper Rifle', 'Covert Sniper Rifle'), ('Covert Knife', 'Covert Knife'), ('Covert Rifle', 'Covert Rifle')], max_length=30)),
                ('precio', models.FloatField()),
                ('coleccion', models.CharField(choices=[('Gamma2', 'Gamma2'), ('Cobblestone', 'Cobblestone'), ('Breakout', 'Breakout')], max_length=13)),
                ('imagen', models.ImageField(blank=True, default='imgSkins/default.png', null=True, upload_to='imgSkins/')),
            ],
        ),
        migrations.AddField(
            model_name='inscriben',
            name='liga',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Liga.Liga'),
        ),
        migrations.AddField(
            model_name='inscriben',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Liga.Adicional'),
        ),
        migrations.AddField(
            model_name='adicional',
            name='liga',
            field=models.ManyToManyField(through='Liga.Inscriben', to='Liga.Liga'),
        ),
        migrations.AddField(
            model_name='adicional',
            name='skin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Liga.Skin'),
        ),
        migrations.AlterUniqueTogether(
            name='inscriben',
            unique_together={('usuario', 'liga', 'fecha')},
        ),
    ]
